language: objective-c  #1
osx_image: xcode9.1 #2
xcode_project: TravisTest.xcodeproj #3
xcode_scheme: TravisTest #4
xcode_sdk: iphonesimulator11.1 #5
script: xcodebuild clean && xcodebuild build -sdk iphonesimulator11.1 -project TravisTest.xcodeproj -scheme TravisTest CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
